### ISSUE TITLE
[iOS] Add Swift Package Manager Support

### ISSUE THREAD

**Issue by yoojinsca** [millicast/millicast-native-sdk#1]
Many modern iOS/tvOS systems use Swift Package Manager.

It would be great to add this support.

**Comment by dbaldassi** [comment]
From what I read, Swift Package Manager is only for Swift project, and the MillicastSDK for iOS/tvOS is an objective-C project.

**Comment by yoojinsca** [comment]
The framework is being distributed as a binary so it shouldn't matter if it was written in Objc / Swift?

Here's an example of your demo code updated to use v1.1.2 and SPM.
https://github.com/yoojinsca/Millicast-ObjC-SDK-iOS-Sample-App-in-Swift

This is an example of what your Framework repo can look like (please disregard naming as this was just a quick test):
https://github.com/yoojinsca/millicast-ios-sdk

Note: Package.swift checksum is use SHA 256
macos Terminal:
openssl sha256 MillicastSDK.xcframework.zip

**Comment by dbaldassi** [comment]
Ok thank you, I will take a look to the Swift Package Manager then.

**Comment by dbaldassi** [comment]
Swift Package manager should be now supported, using this package URL : https://github.com/millicast/millicast-sdk-swift-package
