### ISSUE TITLE
millicast-native-sdk-1.4.2-Windows

### ISSUE THREAD

**Issue by rnkvogel** [millicast/millicast-native-sdk#10]
Building on Windows may require additional steps.
On the MillicastSDKConfig.CMake you may need to add the following.
```
set (VCPKG_ROOT "C:/Dev/vcpkg")
set (ZLIB_INCLUDE_DIR "${VCPKG_ROOT}/include")
set (ZLIB_LIBRARY "${VCPKG_ROOT}/lib")
set (CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
```

Additionally the following .dll were reported (5503) still needed to be added.`zlibd1.dll` and `libcurl-d.dll`

**Comment by dbaldassi** [comment]
I don't think this is required, you can build the SDK without using VCPKG, and have zlib installed somewhere else, so that would bring confusion if we hardcode its location to a VCPKG folder.
The user can add these lines to its own cmake file, before the ``find_package( MillicastSDK REQUIRED )``

**Comment by TylerDovallMPG** [comment]
I'm the one that ran into this issue. I attempted to build without vcpkg first, but the errors were the same. This hardcoded path is a temporary solution, and very specific to my environment, but I still had to define at the very least a `ZLIB_ROOT` manually, as it was not found automatically.
