### ISSUE TITLE
Incorrect color rendering iOS

### ISSUE THREAD

**Issue by wanderingcode** [millicast/millicast-native-sdk#11]
I began writing a iOS viewer app, and I noticed the color rendering is way off.  At first I thought I did something wrong, so I checked the sample app you provide and I see the same color rendering there.  So far I haven't found any options or controls that change the colors on receive stream.  Here is a screen shot showing Chrome and my initial app side by side, and below that is another showing Chrome and the Millicast provided sample app.  The chrome viewer is the bottom set of color bars in both photos.  This example was done broadcasting with Chrome using VP8.  I received the same color shift when I tried AV1 as well.
For reference I tried the Millicast Player MacOS app and at first glance it appears to render colors correctly, although I have not verified the accuracy, they looked the same at first glance.

Is there something that needs to be done to control the color rendering of received streams?  Or is this a bug in the SDK?
Thanks

My App:
![Screenshot 2023-03-16 at 2 58 11 PM-ChromeVsSwiftApp-Colors](https://user-images.githubusercontent.com/87335215/225762715-1fff5c20-c282-4c60-846a-915bc69436c7.png)

Sample App:
![Screenshot 2023-03-16 at 2 59 19 PM-ChromeVsSwiftSampleApp](https://user-images.githubusercontent.com/87335215/225762721-cb0f6d6e-01e4-4ed4-b9e2-46ffb1d4faf8.png)

**Comment by djova-dolby** [comment]
This is fixed in the upcoming 1.8.5 release.

**Comment by djova-dolby** [comment]
Fixed in [1.8.5](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.8.5). The framework is available on github and through [SPM](https://github.com/millicast/millicast-sdk-swift-package/commit/8e8feebf07a75e60f4016498de00f60c586fa247). Due to some CI machine issues it is not yet published to CocoaPods.
