### ISSUE TITLE
MCVideoFrame.frameType() crashes

### ISSUE THREAD

**Issue by wanderingcode** [millicast/millicast-native-sdk#12]
In order to process a video frame I created a MCIosVideoRenderer class and override didReceive.  In that function if I call frameType() on the provided video frame the app crashes with the following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MCVideoFrameImpl frameType]: unrecognized selector sent to instance

I would expect a MCVideoType to be returned so I can verify the correct pixel format and process accordingly.
Any help is appreciated.

**Comment by wanderingcode** [comment]
This has been over a year now.  A lot has changed.  I can confirm it still crashes on 1.7.4
We have not implemented the new async api yet so it will take some time before we can test this on the latest versions.  I'll try to make some time to fit it into our schedule.

**Comment by djova-dolby** [comment]
Honestly, for what its worth sorry for the delay. We only started working on this SDK end of last year, wasn't sure about state of these old untouched issues so they just kind of lingered. I will see that someone in the team takes a look at this. Not sure if this is fixed at all, so we will try to reproduce it and come back with info.

**Comment by wanderingcode** [comment]
I appreciate that. Thanks

**Comment by djova-dolby** [comment]
Ok looking through the Objc part of the SDK I think I found the issue. We will confirm fix and then work to backport it ASAP.

**Comment by djova-dolby** [comment]
No problemo, I will update once release is made. I would definitely suggest moving to the new Async API as soon as possible. It is much more stable and overall just more better.

**Comment by wanderingcode** [comment]
Understood. It's on our list, just not our top priority right now. We will re-evaluate.

**Comment by djova-dolby** [comment]
Releases have been made for [1.8.3](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.8.3) and [1.7.5](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.7.5) with the fix backported.

**Comment by wanderingcode** [comment]
Thank you!
