### ISSUE TITLE
[iOS] New video frame is not sent to renderer when app is in background and the renderer is used to display picture in picture

### ISSUE THREAD

**Issue by Kishimotovn** [millicast/millicast-native-sdk#14]
Hi,

I have an app which display video stream.
When user go into the background, I would like for the stream to be displaying through a Picture in picture window.
I can still hear the audio after going in to the background, but the video freezes.

Please can this be checked? As I don't think there is no documentation on this yet.

**Comment by djova-dolby** [comment]
Which version of the SDK have you tried. I think this has been enabled with the [1.6.0 release](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.6.0).
Please try using the latest [release of v1.7.3](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.7.3).
