### ISSUE TITLE
Hints to use in MacOS M1 app

### ISSUE THREAD

**Issue by ghost** [millicast/millicast-native-sdk#15]
Hi, thank you for the great work here.

I used the iOS package successfully in iOS app, now I'm trying to develop a MacOS app with M1 chip, but couldn't find the package/XCFramework for MacOS. I only find the C++ Dylibs and headers from the releases here.

It seems Swift can't directly call dylibs in C++. Does it mean I need to write a wrapper for each header and function in dylibs in order to use it? Can you give me some guidance on how to use it in MacOS app development?

**Comment by djova-dolby** [comment]
Could you try latest release of SDK? We provide now a [macOS universal framework](https://github.com/millicast/millicast-native-sdk/releases/download/v1.7.1/millicast-native-sdk-1.7.1-macos-Framework.zip) so this should be what you are looking for.
