### ISSUE TITLE
Android SDK | Crash on Samsung A54 (Android 14)

### ISSUE THREAD

**Issue by j12y** [millicast/millicast-native-sdk#17]
See stack trace / crash log here:
https://github.com/orgs/dolbyio-samples/discussions/12

com.millicast:millicast-sdk-android:1.5.0

FYI: @ranjithd14

**Comment by djova-dolby** [comment]
@j12y based on [this comment](https://github.com/orgs/dolbyio-samples/discussions/12#discussioncomment-8296091) this seems like somethign that was fixed with the improvements of the SDK in 1.6 and now even 1.7. Thus I think we can close this one, wdyt?

**Comment by j12y** [comment]
Yep, this sounds like it was resolved in the latest 1.7 release.
