### ISSUE TITLE
Warning: Decklink driver not found in my Linux Mint development environment

### ISSUE THREAD

**Issue by fmoule** [millicast/millicast-native-sdk#20]
Hello.
When i tried to call this function : millicast::Media::get_audio_sources(), i got the following message : 

**Info : MillicastSDK version : 1.7.3

Info : AudioDeviceModule::Create
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
A DeckLink iterator could not be created.  The DeckLink drivers may not be installed.
Warning : A DeckLink iterator could not be created.The DeckLink drivers may not be installed.**

So can you tell me if i should install this driver. Is this issue linked to https://github.com/millicast/millicast-native-sdk/issues/13 ?
For your information, i got this warning in my Linux Mint environment.

Thanks in advance

**Comment by djova-dolby** [comment]
You don't need to install the driver if you don't want to use decklink, the  only side effect is this ugly warning. If you want to use Decklink then yes you need to install.
Unfortunately the Decklink usage is compile time assumed into the SDK so you get these warnings, but there is no other side effects from not having the drivers installed. You just won't have decklink devices.
