### ISSUE TITLE
Xcode 15 support

### ISSUE THREAD

**Issue by wanderingcode** [millicast/millicast-native-sdk#25]
I wanted to try out the MacOS framework today, and I'm running into an issue getting it to compile.  I created a new blank project, imported the framework and updated my search paths.  Then I `import MillicastSDK` in the main view and tried to compile and received the following error:

> Failed to build module 'MillicastSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)'). Please select a toolchain which matches the SDK.

I also tried downloading swfit 5.7.2 and changing the toolchain, and received errors about unknown arguments in the swift compiler

I'm using Xcode 15.3 on MacOS 14.4.1.    Unfortunately Xcode 14.3 isn't supported on MacOS 14.4.1 so I can't downgrade Xcode.

Am I missing a build setting?  Is there another way to get the framework working on Xcode 15?

Any help would be appreciated.

**Comment by FabienLavocat** [comment]
What version of the iOS SDK are you using? I've loaded our latest release, [version 1.8.4](https://github.com/millicast/millicast-native-sdk/releases/tag/v1.8.4) and don't get that problem.

**Comment by wanderingcode** [comment]
I am trying to build a MacOS app with the MacOS framework version 1.8.4
Thanks

**Comment by FabienLavocat** [comment]
Oh I'm sorry, I was doing my test with iOS instead of MacOS. I still get it to work properly on MacOS tho.

![image](https://github.com/millicast/millicast-native-sdk/assets/4154532/b836ef76-8e4c-4409-b879-710ebf5dbcd9)

I had to make sure to copy the files when importing the SDK into my app (simple drag & drop from Finder of the `MillicastSDK.framework` folder.

**Comment by wanderingcode** [comment]
Thank you for checking.  I didn't think to try another system, and it works as expected on my laptop, so I obviously have something wrong in my system.
I appreciate your time.
