### ISSUE TITLE
[iOS] Add Bitcode support

### ISSUE THREAD

**Issue by yoojinsca** [millicast/millicast-native-sdk#4]
This will allow the app to reduce it's size when downloaded on a device.

More info here:
https://help.apple.com/xcode/mac/11.0/index.html?localePath=en.lproj#/devde46df08a

**Comment by murillo128** [comment]
@goddino can you check if this is feasible?

**Comment by dbaldassi** [comment]
The bitcode is already enabled

**Comment by yoojinsca** [comment]
Apologies I did not see any documentation on this. 
Just wondering have you tried archiving and publishing to the App Store with an iOS app that has bitcode enabled?

The reason I thought bitcode was not supported was because of the following:

1) When I try to detect bitcode on the universal framework I am unable to see it (version 1.0 and 1.1.2)
ie.
` otool -l  MillicastSDK.framework/MillicastSDK  | grep __LLVM`
 
 2) I had to turn bitcode support off on our CI server bitrise else it would fail archiving with:
` -[NSNull path]: unrecognized selector sent to instance`

**Comment by dbaldassi** [comment]
Yes we tried archiving an iOS app and push it into testflight, but only with the arm64 only framework.

For the universal framework., if you specify the arch, you can see the segname __LLVM.
`otool -arch arm64 -l MillicastSDK.framework/MillicastSDK |  grep __LLVM`

**Comment by yoojinsca** [comment]
ok. thanks for the quick replies.
